### ISSUE TITLE
Corps Bugged For Everyone (Since Aug 13th)

### ISSUE THREAD

**Issue by CantBeKarma** [HitsparkInteractive/NinOnline#32] opened 2021-08-18 03:21 UTC
## Problem description

Since the release of Corps, there has been only 1 update (14th) where it fixed players getting stuck in Corps maps like PB and 7SM but the system itself has been bugged where Kages get an error saying "No Access" and they cannot assign leaders to the Corps. Leaf/Sand/Mist have all posted on discord saying they cannot make anyone a leader. Meaning that since the 13th no one has been able to join an organization (corps) in game at all. It's also bugged for the Akatsuki where GMs cannot set someone properly as the leader. 

## Steps to reproduce issue

1. Kages have constantly said on discord that Corps are bugged ("No Access" message).
2. No one is in an organization (Corps) in game, which prove it's truly bugged.

## Observed result
I can see that the windows/GUI of the corps are barebones right now but they should at least be functional IMO. I think people just assumed this is being worked on but I haven't heard an official statement saying they're being fixed and other updates involving features are being pushed out instead it seems.

## Expected result
I personally think that it should be a priority to get the functionality working, even if it looks ugly there is no need to work on the looks/GUI first since Orgs (Corps) are a major part of Nin Online right now. I'm just posting this bug report here for the sake of logging down the bug. Thanks!

**Comment by RorySoh** [comment] 2021-08-18 17:42
I've been shouting into the void of words lost into the oblivion called the Nin communtiy since 13th August that we're fixing the issues with it. The user interface is also temporary.

The bugs should be fixed as of today's update.

**Closed as completed by RorySoh** 2021-08-18 17:42 UTC
Labels: bug

**Comment by RorySoh** [comment] 2021-08-18 17:46
Confirmed with a player that it's working
