### ISSUE TITLE
High GPU Usage spikes on login screen

### ISSUE THREAD

**Issue by ghost** [HitsparkInteractive/NinOnline#76] opened 2021-09-12 20:51 UTC
## Problem description

When game is loaded and u are on login screen your GPU usage and following this GPU Temps are going crazy.

## Steps to reproduce issue

1. Open a game
2. Be on login screen
3. Open Task Manager

## Observed result

90%+ GPU Usage and High Temps

## Expected result

Normal GPU Usage

## More details

**Affected Client Version:** Inochi 3.5.5e

**First noticed:** 12.09.21

https://user-images.githubusercontent.com/8196001/133002416-8efede25-f918-42dd-ab8d-cefaaef5083c.mp4

**Comment by RorySoh** [comment] 2021-10-08 21:52
This is caused by not FPS locking the game. By definition, that means wanting the game to render as many frames as possible, more than necessary. "Done with rendering a frame? If there is GPU power to spare, render another."

We might resolve this by forcing some arbitrary FPS lock in menus.

**Comment by RorySoh** [comment] 2021-10-21 08:34
Fixed in next client update

**Closed as completed by RorySoh** 2021-10-21 08:34 UTC
Labels: bug
